name: Database
on:
  push:
    branches:
      - main
    paths: &paths
      - "database/**"
      - "common/**"
      - "*.json"
      - "bun.lock"
      - ".github/workflows/database.yml"
  pull_request:
    paths: *paths
jobs:
  database:
    name: Database
    runs-on: ubuntu-latest
    concurrency: ci-database-${{ github.ref }}
    env:
      DATABASE_URL: "${{ secrets.DATABASE_URL }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Packages
        run: bun ci --filter . --filter ./common --filter ./database

      - name: Typecheck Database
        run: bun typecheck
        working-directory: ./database

      - name: Generate Migrations
        run: bun run build && bun db:generate
        working-directory: ./database

      - name: Deploy Migrations
        if: github.ref_name == 'main'
        run: bun db:push -- --force
        working-directory: ./database
